/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taskeroo/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks with optional filtering */
        get: operations["TaskerooController_listTasks"];
        put?: never;
        /** Create a new task */
        post: operations["TaskerooController_createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taskeroo/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task by ID */
        get: operations["TaskerooController_getTask"];
        put?: never;
        post?: never;
        /** Delete a task */
        delete: operations["TaskerooController_deleteTask"];
        options?: never;
        head?: never;
        /** Update task description */
        patch: operations["TaskerooController_updateTask"];
        trace?: never;
    };
    "/taskeroo/tasks/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign a task to someone */
        patch: operations["TaskerooController_assignTask"];
        trace?: never;
    };
    "/taskeroo/tasks/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a comment to a task */
        post: operations["TaskerooController_addComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/taskeroo/tasks/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change task status */
        patch: operations["TaskerooController_changeStatus"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateTaskDto: {
            /**
             * @description Name of the task
             * @example Implement user authentication
             */
            name: string;
            /**
             * @description Detailed description of the task
             * @example Add JWT-based authentication to the API
             */
            description: string;
            /**
             * @description Name of the assignee (for AI agents)
             * @example AgentAlpha
             */
            assignee?: string;
            /**
             * @description Session ID for tracking AI agent work
             * @example session-123-abc
             */
            sessionId?: string;
        };
        Comment: Record<string, never>;
        TaskResponseDto: {
            /**
             * @description Unique identifier for the task
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Name of the task
             * @example Implement user authentication
             */
            name: string;
            /**
             * @description Detailed description of the task
             * @example Add JWT-based authentication to the API
             */
            description: string;
            /**
             * @description Current status of the task
             * @example not started
             * @enum {string}
             */
            status: "not started" | "in progress" | "for review" | "done";
            /**
             * @description Name of the assignee (for AI agents)
             * @example AgentAlpha
             */
            assignee?: string | null;
            /**
             * @description Session ID for tracking AI agent work
             * @example session-123-abc
             */
            sessionId?: string | null;
            /**
             * @description Comments associated with the task
             * @example [
             *       {
             *         "id": "cmt-001",
             *         "taskId": "123e4567-e89b-12d3-a456-426614174000",
             *         "commenterName": "John Doe",
             *         "content": "Please prioritize this task.",
             *         "createdAt": "2025-11-03T11:00:00.000Z"
             *       }
             *     ]
             */
            comments: components["schemas"]["Comment"][];
            /**
             * @description Task creation timestamp
             * @example 2025-11-03T10:30:00.000Z
             */
            createdAt: string;
            /**
             * @description Task last update timestamp
             * @example 2025-11-03T12:45:00.000Z
             */
            updatedAt: string;
        };
        UpdateTaskDto: {
            /**
             * @description Updated description of the task
             * @example Add JWT-based authentication with refresh tokens
             */
            description: string;
        };
        AssignTaskDto: {
            /**
             * @description Name of the assignee (can be empty to unassign)
             * @example AgentAlpha
             */
            assignee?: Record<string, never>;
        };
        CreateCommentDto: {
            /**
             * @description Name of the person or agent commenting
             * @example AgentBeta
             */
            commenterName: string;
            /**
             * @description Content of the comment
             * @example Task completed successfully. All tests passing.
             */
            content: string;
        };
        CommentResponseDto: {
            /**
             * @description Unique identifier for the comment
             * @example 123e4567-e89b-12d3-a456-426614174001
             */
            id: string;
            /**
             * @description ID of the task this comment belongs to
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            taskId: string;
            /**
             * @description Name of the person/agent who created the comment
             * @example AgentAlpha
             */
            commenterName: string;
            /**
             * @description Content of the comment
             * @example Started working on this task
             */
            content: string;
            /**
             * @description Comment creation timestamp
             * @example 2025-11-03T10:30:00.000Z
             */
            createdAt: string;
        };
        ChangeStatusDto: {
            /**
             * @description New status for the task
             * @example in progress
             * @enum {string}
             */
            status: "not started" | "in progress" | "for review" | "done";
            /**
             * @description Comment required when marking task as done
             * @example All requirements met and tests passing
             */
            comment?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a greeting message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    TaskerooController_listTasks: {
        parameters: {
            query?: {
                /** @description Filter tasks by assignee name */
                assignee?: string;
                /** @description Filter tasks by session ID */
                sessionId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"][];
                };
            };
        };
    };
    TaskerooController_createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            /** @description Task created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            /** @description Task updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_assignTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignTaskDto"];
            };
        };
        responses: {
            /** @description Task assigned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_addComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            /** @description Comment added successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusDto"];
            };
        };
        responses: {
            /** @description Status changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Invalid status transition or comment required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
