/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taskeroo/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks with optional filtering and pagination */
        get: operations["TaskerooController_listTasks"];
        put?: never;
        /** Create a new task */
        post: operations["TaskerooController_createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taskeroo/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task by ID */
        get: operations["TaskerooController_getTask"];
        put?: never;
        post?: never;
        /** Delete a task */
        delete: operations["TaskerooController_deleteTask"];
        options?: never;
        head?: never;
        /** Update task description */
        patch: operations["TaskerooController_updateTask"];
        trace?: never;
    };
    "/api/v1/taskeroo/tasks/{id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Assign a task to someone */
        patch: operations["TaskerooController_assignTask"];
        trace?: never;
    };
    "/api/v1/taskeroo/tasks/{id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a comment to a task */
        post: operations["TaskerooController_addComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/taskeroo/tasks/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change task status */
        patch: operations["TaskerooController_changeStatus"];
        trace?: never;
    };
    "/api/v1/wikiroo/pages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List wiki pages without content */
        get: operations["WikirooController_listPages"];
        put?: never;
        /** Create a new wiki page */
        post: operations["WikirooController_createPage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wikiroo/pages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a wiki page by ID */
        get: operations["WikirooController_getPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authz/clients/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new OAuth 2.0 client (Dynamic Client Registration)
         * @description Implements RFC 7591 Dynamic Client Registration for OAuth 2.0. Validates client metadata, generates credentials, and persists the client configuration. Requires authorization_code and refresh_token grant types with PKCE support per MCP specification.
         */
        post: operations["ClientRegistrationController_registerClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authz/clients/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve client registration information
         * @description Returns the registration metadata for a client. The client_secret is NOT included in the response for security reasons.
         */
        get: operations["ClientRegistrationController_getClient"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/authz/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all registered clients (Admin)
         * @description Returns a list of all registered OAuth clients. Intended for administrative purposes. Client secrets are not included.
         */
        get: operations["ClientRegistrationController_listClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all MCP servers with pagination */
        get: operations["McpRegistryController_listServers"];
        put?: never;
        /** Register a new MCP server */
        post: operations["McpRegistryController_createServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/servers/{serverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get MCP server by UUID or provided ID */
        get: operations["McpRegistryController_getServer"];
        put?: never;
        post?: never;
        /** Delete MCP server (must have no dependencies) */
        delete: operations["McpRegistryController_deleteServer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/servers/{serverId}/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all scopes for an MCP server */
        get: operations["McpRegistryController_listScopes"];
        put?: never;
        /** Create MCP scope(s) for a server */
        post: operations["McpRegistryController_createScopes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/servers/{serverId}/scopes/{scopeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific MCP scope */
        get: operations["McpRegistryController_getScope"];
        put?: never;
        post?: never;
        /** Delete MCP scope (must have no mappings) */
        delete: operations["McpRegistryController_deleteScope"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/servers/{serverId}/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all connections for an MCP server */
        get: operations["McpRegistryController_listConnections"];
        put?: never;
        /** Create OAuth connection for an MCP server */
        post: operations["McpRegistryController_createConnection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/connections/{connectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific connection */
        get: operations["McpRegistryController_getConnection"];
        put?: never;
        post?: never;
        /** Delete connection (must have no mappings) */
        delete: operations["McpRegistryController_deleteConnection"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/servers/{serverId}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create scope mapping */
        post: operations["McpRegistryController_createMapping"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/servers/{serverId}/scopes/{scopeId}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List downstream scopes for an MCP scope */
        get: operations["McpRegistryController_listMappings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mcp/mappings/{mappingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete scope mapping */
        delete: operations["McpRegistryController_deleteMapping"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateTaskDto: {
            /**
             * @description Name of the task
             * @example Implement user authentication
             */
            name: string;
            /**
             * @description Detailed description of the task
             * @example Add JWT-based authentication to the API
             */
            description: string;
            /**
             * @description Name of the assignee (for AI agents)
             * @example AgentAlpha
             */
            assignee?: string;
            /**
             * @description Session ID for tracking AI agent work
             * @example session-123-abc
             */
            sessionId?: string;
        };
        CommentResponseDto: {
            /**
             * @description Unique identifier for the comment
             * @example 123e4567-e89b-12d3-a456-426614174001
             */
            id: string;
            /**
             * @description ID of the task this comment belongs to
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            taskId: string;
            /**
             * @description Name of the person/agent who created the comment
             * @example AgentAlpha
             */
            commenterName: string;
            /**
             * @description Content of the comment
             * @example Started working on this task
             */
            content: string;
            /**
             * @description Comment creation timestamp
             * @example 2025-11-03T10:30:00.000Z
             */
            createdAt: string;
        };
        TaskResponseDto: {
            /**
             * @description Unique identifier for the task
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Name of the task
             * @example Implement user authentication
             */
            name: string;
            /**
             * @description Detailed description of the task
             * @example Add JWT-based authentication to the API
             */
            description: string;
            /**
             * @description Current status of the task
             * @example NOT_STARTED
             * @enum {string}
             */
            status: "NOT_STARTED" | "IN_PROGRESS" | "FOR_REVIEW" | "DONE";
            /**
             * @description Name of the assignee (for AI agents)
             * @example AgentAlpha
             */
            assignee?: string | null;
            /**
             * @description Session ID for tracking AI agent work
             * @example session-123-abc
             */
            sessionId?: string | null;
            /**
             * @description Comments associated with the task
             * @example [
             *       {
             *         "id": "cmt-001",
             *         "taskId": "123e4567-e89b-12d3-a456-426614174000",
             *         "commenterName": "John Doe",
             *         "content": "Please prioritize this task.",
             *         "createdAt": "2025-11-03T11:00:00.000Z"
             *       }
             *     ]
             */
            comments: components["schemas"]["CommentResponseDto"][];
            /**
             * @description Task creation timestamp
             * @example 2025-11-03T10:30:00.000Z
             */
            createdAt: string;
            /**
             * @description Task last update timestamp
             * @example 2025-11-03T12:45:00.000Z
             */
            updatedAt: string;
        };
        UpdateTaskDto: {
            /**
             * @description Updated description of the task
             * @example Add JWT-based authentication with refresh tokens
             */
            description: string;
        };
        AssignTaskDto: {
            /**
             * @description Name of the assignee (can be empty to unassign)
             * @example AgentAlpha
             */
            assignee?: Record<string, never>;
            /**
             * @description Session ID for tracking AI agent work
             * @example session-123-abc
             */
            sessionId?: string;
        };
        TaskListResponseDto: {
            /** @description List of tasks */
            items: components["schemas"]["TaskResponseDto"][];
            /**
             * @description Total number of tasks matching the filters
             * @example 42
             */
            total: number;
            /**
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * @description Number of items per page
             * @example 20
             */
            limit: number;
            /**
             * @description Total number of pages
             * @example 3
             */
            totalPages: number;
        };
        CreateCommentDto: {
            /**
             * @description Name of the person or agent commenting
             * @example AgentBeta
             */
            commenterName: string;
            /**
             * @description Content of the comment
             * @example Task completed successfully. All tests passing.
             */
            content: string;
        };
        TaskChangeStatusDto: {
            /**
             * @description New status for the task
             * @example IN_PROGRESS
             * @enum {string}
             */
            status: "NOT_STARTED" | "IN_PROGRESS" | "FOR_REVIEW" | "DONE";
            /**
             * @description Comment required when marking task as done
             * @example All requirements met and tests passing
             */
            comment?: string;
        };
        CreatePageDto: {
            /**
             * @description Title of the wiki page
             * @example How to onboard new agents
             */
            title: string;
            /**
             * @description Markdown content of the page
             * @example # Welcome to Wikiroo
             *     This is the onboarding guide.
             */
            content: string;
            /**
             * @description Author of the page
             * @example Agent Roo
             */
            author: string;
        };
        PageResponseDto: {
            /**
             * @description Unique identifier for the page
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Title of the wiki page
             * @example How to onboard new agents
             */
            title: string;
            /**
             * @description Markdown content of the wiki page
             * @example # Welcome to Wikiroo
             */
            content: string;
            /**
             * @description Author of the wiki page
             * @example Agent Roo
             */
            author: string;
            /**
             * @description Creation timestamp
             * @example 2025-01-01T12:00:00.000Z
             */
            createdAt: string;
            /**
             * @description Last update timestamp
             * @example 2025-01-02T15:30:00.000Z
             */
            updatedAt: string;
        };
        PageSummaryDto: {
            /**
             * @description Unique identifier for the page
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Title of the wiki page
             * @example How to onboard new agents
             */
            title: string;
            /**
             * @description Author of the wiki page
             * @example Agent Roo
             */
            author: string;
            /**
             * @description Creation timestamp
             * @example 2025-01-01T12:00:00.000Z
             */
            createdAt: string;
            /**
             * @description Last update timestamp
             * @example 2025-01-02T15:30:00.000Z
             */
            updatedAt: string;
        };
        PageListResponseDto: {
            /** @description List of wiki pages */
            items: components["schemas"]["PageSummaryDto"][];
        };
        RegisterClientDto: {
            /**
             * @description Human-readable name of the client
             * @example My OAuth Client
             */
            client_name: string;
            /**
             * @description Array of redirect URIs for authorization callbacks
             * @example [
             *       "https://example.com/callback"
             *     ]
             */
            redirect_uris: string[];
            /**
             * @description Grant types the client will use. Must include authorization_code and refresh_token per MCP requirements.
             * @example [
             *       "authorization_code",
             *       "refresh_token"
             *     ]
             */
            grant_types: ("authorization_code" | "refresh_token" | "client_credentials")[];
            /**
             * @description Authentication method for the token endpoint
             * @example client_secret_basic
             * @enum {string}
             */
            token_endpoint_auth_method: "client_secret_basic" | "client_secret_post" | "none";
            /**
             * @description Requested scopes for the client
             * @example [
             *       "openid",
             *       "profile",
             *       "email"
             *     ]
             */
            scope?: string[];
            /**
             * @description Contact emails for the client registration
             * @example [
             *       "admin@example.com"
             *     ]
             */
            contacts?: string[];
            /**
             * @description PKCE code challenge method. Must be S256 for authorization_code grant.
             * @example S256
             */
            code_challenge_method?: string;
        };
        ClientRegistrationResponseDto: {
            /**
             * @description Unique client identifier
             * @example 8f7a9c2e-4b1d-4e6f-9a2b-3c4d5e6f7a8b
             */
            client_id: string;
            /**
             * @description Client secret for confidential clients
             * @example ZXhhbXBsZV9zZWNyZXRfa2V5
             */
            client_secret?: Record<string, never> | null;
            /**
             * @description Human-readable name of the client
             * @example My OAuth Client
             */
            client_name: string;
            /**
             * @description Array of redirect URIs for authorization callbacks
             * @example [
             *       "https://example.com/callback"
             *     ]
             */
            redirect_uris: string[];
            /**
             * @description Grant types the client is authorized to use
             * @example [
             *       "authorization_code",
             *       "refresh_token"
             *     ]
             */
            grant_types: ("authorization_code" | "refresh_token" | "client_credentials")[];
            /**
             * @description Authentication method for the token endpoint
             * @example client_secret_basic
             * @enum {string}
             */
            token_endpoint_auth_method: "client_secret_basic" | "client_secret_post" | "none";
            /**
             * @description Scopes granted to the client
             * @example [
             *       "openid",
             *       "profile",
             *       "email"
             *     ]
             */
            scope?: string[] | null;
            /**
             * @description Contact emails for the client
             * @example [
             *       "admin@example.com"
             *     ]
             */
            contacts?: string[] | null;
            /**
             * @description PKCE code challenge method
             * @example S256
             */
            code_challenge_method?: Record<string, never> | null;
            /**
             * @description Client registration timestamp (ISO 8601)
             * @example 2025-11-05T08:00:00.000Z
             */
            client_id_issued_at: string;
        };
        CreateServerDto: {
            /**
             * @description Human-readable unique identifier for the MCP server
             * @example github-integration
             */
            providedId: string;
            /**
             * @description Display name of the MCP server
             * @example GitHub Integration
             */
            name: string;
            /**
             * @description Short description of the MCP server
             * @example Provides access to GitHub repositories and issues
             */
            description: string;
        };
        CreateConnectionDto: {
            /**
             * @description Friendly name to identify this OAuth connection
             * @example GitHub OAuth Connection
             */
            friendlyName: string;
            /**
             * @description OAuth client ID for the downstream provider
             * @example github_client_abc123
             */
            clientId: string;
            /**
             * @description OAuth client secret for the downstream provider
             * @example secret_xyz789
             */
            clientSecret: string;
            /**
             * @description OAuth authorization endpoint URL
             * @example https://github.com/login/oauth/authorize
             */
            authorizeUrl: string;
            /**
             * @description OAuth token endpoint URL
             * @example https://github.com/login/oauth/access_token
             */
            tokenUrl: string;
        };
        CreateMappingDto: {
            /**
             * @description MCP scope ID to map from
             * @example tool:read
             */
            scopeId: string;
            /**
             * @description Connection ID that owns this mapping
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            connectionId: string;
            /**
             * @description Downstream OAuth scope string
             * @example repo:read
             */
            downstreamScope: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a greeting message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    TaskerooController_listTasks: {
        parameters: {
            query?: {
                /** @description Filter tasks by assignee name */
                assignee?: string;
                /** @description Filter tasks by session ID */
                sessionId?: string;
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Items per page (1-100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponseDto"];
                };
            };
        };
    };
    TaskerooController_createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskDto"];
            };
        };
        responses: {
            /** @description Task created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTaskDto"];
            };
        };
        responses: {
            /** @description Task updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_assignTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignTaskDto"];
            };
        };
        responses: {
            /** @description Task assigned successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_addComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            /** @description Comment added successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TaskerooController_changeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskChangeStatusDto"];
            };
        };
        responses: {
            /** @description Status changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponseDto"];
                };
            };
            /** @description Invalid status transition or comment required */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WikirooController_listPages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of wiki pages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageListResponseDto"];
                };
            };
        };
    };
    WikirooController_createPage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePageDto"];
            };
        };
        responses: {
            /** @description Wiki page created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseDto"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WikirooController_getPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wiki page identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wiki page retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseDto"];
                };
            };
        };
    };
    ClientRegistrationController_registerClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterClientDto"];
            };
        };
        responses: {
            /** @description Client registered successfully with generated credentials */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRegistrationResponseDto"];
                };
            };
            /** @description Invalid client metadata (missing fields, invalid redirect URIs, unsupported grant types, or PKCE not configured) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A client with this name is already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRegistrationController_getClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Client registration information retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRegistrationResponseDto"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientRegistrationController_listClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of registered clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRegistrationResponseDto"][];
                };
            };
        };
    };
    McpRegistryController_listServers: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of servers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_createServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateServerDto"];
            };
        };
        responses: {
            /** @description Server created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server with providedId already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_getServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID or provided ID */
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_deleteServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID */
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server has dependencies */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_listScopes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID */
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of scopes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_createScopes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID */
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope(s) created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_getScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID */
                serverId: string;
                /** @description Scope ID string */
                scopeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_deleteScope: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID */
                serverId: string;
                /** @description Scope ID string */
                scopeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scope deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope has mappings */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_listConnections: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID */
                serverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of connections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_createConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID */
                serverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConnectionDto"];
            };
        };
        responses: {
            /** @description Connection created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connection name conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_getConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection UUID */
                connectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_deleteConnection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Connection UUID */
                connectionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Connection has mappings */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_createMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID */
                serverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMappingDto"];
            };
        };
        responses: {
            /** @description Mapping created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid mapping */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope or connection not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_listMappings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Server UUID */
                serverId: string;
                /** @description Scope ID string */
                scopeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of mappings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Scope not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    McpRegistryController_deleteMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Mapping UUID */
                mappingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mapping deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mapping not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
