import { ThreadsService as GeneratedThreadsService, type ThreadMessageResponseDto, type ListThreadMessagesResponseDto } from "@taico/client";
import type { ThreadListItem, Thread } from './types';

// Wrapper around autogenerated API client
export class ThreadsService {
  static async listThreads(): Promise<{ items: ThreadListItem[] }> {
    const response = await GeneratedThreadsService.threadsControllerListThreads();
    return { items: response.items };
  }

  static async getThread(id: string): Promise<Thread> {
    return await GeneratedThreadsService.threadsControllerGetThread(id);
  }

  static async createThread(input?: { title?: string; parentTaskId?: string }): Promise<Thread> {
    return await GeneratedThreadsService.threadsControllerCreateThread({
      title: input?.title,
      parentTaskId: input?.parentTaskId,
    });
  }

  static async getThreadForTask(taskId: string): Promise<Thread | null> {
    const limit = 50;
    let page = 1;

    while (true) {
      const response = await GeneratedThreadsService.threadsControllerListThreads(page, limit);
      const threads = await Promise.all(
        response.items.map((thread) => GeneratedThreadsService.threadsControllerGetThread(thread.id)),
      );

      const matchingThread = threads.find((thread) =>
        thread.tasks.some((task) => task.id === taskId),
      );

      if (matchingThread) {
        return matchingThread;
      }

      if (page >= response.totalPages) {
        return null;
      }

      page += 1;
    }
  }

  static async deleteThread(id: string): Promise<void> {
    await GeneratedThreadsService.threadsControllerDeleteThread(id);
  }

  static async listMessages(threadId: string, page: number = 1, limit: number = 50): Promise<ListThreadMessagesResponseDto> {
    return await GeneratedThreadsService.threadsControllerListMessages(threadId, page, limit);
  }

  static async createMessage(threadId: string, content: string): Promise<ThreadMessageResponseDto> {
    return await GeneratedThreadsService.threadsControllerCreateMessage(threadId, { content });
  }
}
