export const ErrorCodes = {
  // Task errors
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_NOT_ASSIGNED: 'TASK_NOT_ASSIGNED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  COMMENT_REQUIRED: 'COMMENT_REQUIRED',

  // Wiki errors
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',

  // Authorization Server - Client Registration errors
  CLIENT_ALREADY_REGISTERED: 'CLIENT_ALREADY_REGISTERED',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  INVALID_REDIRECT_URI: 'INVALID_REDIRECT_URI',
  INVALID_GRANT_TYPE: 'INVALID_GRANT_TYPE',
  INVALID_TOKEN_ENDPOINT_AUTH_METHOD: 'INVALID_TOKEN_ENDPOINT_AUTH_METHOD',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // MCP Registry errors
  SERVER_NOT_FOUND: 'SERVER_NOT_FOUND',
  SERVER_ALREADY_EXISTS: 'SERVER_ALREADY_EXISTS',
  SCOPE_NOT_FOUND: 'SCOPE_NOT_FOUND',
  SCOPE_ALREADY_EXISTS: 'SCOPE_ALREADY_EXISTS',
  CONNECTION_NOT_FOUND: 'CONNECTION_NOT_FOUND',
  CONNECTION_NAME_CONFLICT: 'CONNECTION_NAME_CONFLICT',
  MAPPING_NOT_FOUND: 'MAPPING_NOT_FOUND',
  SERVER_HAS_DEPENDENCIES: 'SERVER_HAS_DEPENDENCIES',
  SCOPE_HAS_MAPPINGS: 'SCOPE_HAS_MAPPINGS',
  CONNECTION_HAS_MAPPINGS: 'CONNECTION_HAS_MAPPINGS',
  INVALID_MAPPING: 'INVALID_MAPPING',

  // Generic errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
