export const ErrorCodes = {
  // Task errors
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_NOT_ASSIGNED: 'TASK_NOT_ASSIGNED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  COMMENT_REQUIRED: 'COMMENT_REQUIRED',

  // Wiki errors
  PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',

  // Authorization Server - Client Registration errors
  CLIENT_ALREADY_REGISTERED: 'CLIENT_ALREADY_REGISTERED',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  INVALID_REDIRECT_URI: 'INVALID_REDIRECT_URI',
  INVALID_GRANT_TYPE: 'INVALID_GRANT_TYPE',
  INVALID_TOKEN_ENDPOINT_AUTH_METHOD: 'INVALID_TOKEN_ENDPOINT_AUTH_METHOD',
  PKCE_REQUIRED: 'PKCE_REQUIRED',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Generic errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
