/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all clients */
        get: operations["ClientController_listClients"];
        put?: never;
        /** Create a new client */
        post: operations["ClientController_createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a client by ID */
        get: operations["ClientController_getClientById"];
        put?: never;
        post?: never;
        /** Delete a client */
        delete: operations["ClientController_deleteClient"];
        options?: never;
        head?: never;
        /** Update a client */
        patch: operations["ClientController_updateClient"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ClientDto: {
            /**
             * Format: uuid
             * @description The unique identifier of the client
             * @example a1b2c3d4-e5f6-7890-1234-567890abcdef
             */
            id: string;
            /**
             * @description The name of the client. Must be between 3 and 120 characters.
             * @example Acme Corporation
             */
            name: string;
        };
        ListClientsResponseDto: {
            /** @description A list of clients, each containing their unique identifier and name. */
            clients: components["schemas"]["ClientDto"][];
        };
        CreateClientDto: {
            /**
             * @description The name of the client. Must be between 3 and 120 characters.
             * @example Acme Corporation
             */
            name: string;
        };
        UpdateClientDto: {
            /**
             * @description The name of the client. Must be between 3 and 120 characters.
             * @example Acme Corporation
             */
            name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientController_listClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved list of clients */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListClientsResponseDto"];
                };
            };
        };
    };
    ClientController_createClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientDto"];
            };
        };
        responses: {
            /** @description Successfully created a new client */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDto"];
                };
            };
        };
    };
    ClientController_getClientById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the client */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDto"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientController_deleteClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the client */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully deleted client */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ClientController_updateClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the client */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientDto"];
            };
        };
        responses: {
            /** @description Successfully updated client */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDto"];
                };
            };
            /** @description Client not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
