export const OutboxEventTypes = {
  TASK_CREATED: 'tasks.created.v1',
  TASK_UPDATED: 'tasks.updated.v1',
  TASK_ASSIGNED: 'tasks.assigned.v1',
  TASK_COMMENT_ADDED: 'tasks.comment-added.v1',
  TASK_INPUT_REQUEST_ANSWERED: 'tasks.input-request-answered.v1',
  TASK_ARTEFACT_ADDED: 'tasks.artefact-added.v1',
  THREAD_UPDATED: 'threads.updated.v1',
  THREAD_DELETED: 'threads.deleted.v1',
  THREAD_CREATED: 'threads.created.v1',
  THREAD_MESSAGE_CREATED: 'threads.message-created.v1',
  CONTEXT_BLOCK_CREATED: 'context.blocks.created.v1',
  CONTEXT_BLOCK_UPDATED: 'context.blocks.updated.v1',
  CONTEXT_BLOCK_DELETED: 'context.blocks.deleted.v1',
  AGENT_CREATED: 'agents.created.v1',
  AGENT_UPDATED: 'agents.updated.v1',
  AGENT_DELETED: 'agents.deleted.v1',
  TASK_STATUS_CHANGED: 'tasks.status-changed.v1',
  TASK_DELETED: 'tasks.deleted.v1',
} as const;
